# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: FAIR modelling of enzyme kinetics by EnzymeML and Jupyter Notebooks
author: Hannah Dienhart
copyright: "2022"
logo: EnzML-favicon-32x32.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
# Not used, pdf is builed from HTML
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/HannahDi/master-thesis  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  #use_issues_button: true
  use_repository_button: true
